name: labor
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  flutter_svg: ^2.0.2
  flutter_animated_dialog: ^2.0.1
  async_loader: ^0.1.2
  brasil_fields: ^1.9.1
  share_plus: ^6.3.1
  path_provider: ^2.0.13
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  firebase_auth: ^4.4.2
  firebase_auth_web: ^5.3.2
  google_maps_flutter: ^0.5.20+1
  device_preview: ^1.1.0
  geolocator: ^5.1.3
  firebase_app_check: ^0.1.2+2
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/blue.png
    - assets/images/
